### PR TITLE
search: allow focusing on input with `Ctrl+K` or `/`

### PR DESCRIPTION
**Pull request by brunodeangelis**

### CODE REVIEW

**Comment by gingerBill** [comment]
I won't merge this as I want to make it look visually obvious that this will work, not just have a hidden shortcut.

**Comment by brunodeangelis** [comment]
> I won't merge this as I want to make it look visually obvious that this will work, not just have a hidden shortcut.
> 

image

would you prefer something like this?

**Comment by gingerBill** [comment]
Yes

**Comment by gingerBill** [comment]
If it says "Ctrl+K" for non-Mac targets too, then yes please!

**Comment by brunodeangelis** [comment]
> If it says "Ctrl+K" for non-Mac targets too, then yes please!

would this be an automatic OS detection or just put it along with the one for mac?

**Comment by Kelimion** [comment]
I think you can sniff the UA for macOS from JS or something?

**Comment by brunodeangelis** [comment]
> I think you can sniff the UA for macOS from JS or something?

yes you can see here: https://github.com/odin-lang/pkg.odin-lang.org/pull/16/commits/0a85c0f5d613313fa3c773e693a8dfb2e8eddc6b#diff-bbbd919259c9de0532fc89c88ba69abe64a6ee4dd7f1c8d560fbbd447d96a3efR3-R17

**Pull request closed without merging**
